pipeline {
    agent any

    stages {
        stage('Preparation') {
            steps {
                script {
                    // Set the workspace for the Python project
                    env.WORKSPACE_PATH = "${env.WORKSPACE}\\Ch05\\05_02-publish-reports"
                }
            }
        }

        stage('Create Virtual Environment') {
            steps {
                bat 'C:\Users\ababa\AppData\Local\Microsoft\WindowsApps\pythone.exe -m venv ${env.WORKSPACE_PATH}\\venv'
            }
        }

        stage('Upgrade Dependencies') {
            steps {
                bat "${env.WORKSPACE_PATH}\\venv\\Scripts\\pip install --upgrade --requirement ${env.WORKSPACE_PATH}\\requirements.txt"
            }
        }

        stage('Linting') {
            steps {
                bat "${env.WORKSPACE_PATH}\\venv\\Scripts\\flake8 --ignore=E501,E231 ${env.WORKSPACE_PATH}\\*.py"
                bat "${env.WORKSPACE_PATH}\\venv\\Scripts\\pylint --errors-only --disable=C0301 --disable=C0326 ${env.WORKSPACE_PATH}\\*.py"
            }
        }

        stage('Testing with Coverage') {
            steps {
                bat "${env.WORKSPACE_PATH}\\venv\\Scripts\\coverage run -m pytest -v ${env.WORKSPACE_PATH}\\test_*.py --junitxml=${env.WORKSPACE_PATH}\\pytest_junit.xml"
            }
        }

        stage('Post-Build Actions') {
            steps {
                bat "${env.WORKSPACE_PATH}\\venv\\Scripts\\coverage xml"
                // Add additional steps to publish results if needed
            }
        }
    }
}
